### ISSUE TITLE
Suggestion for update hubpress section

### ISSUE THREAD

**Issue by dakeshi** [HubPress/dev.hubpress.io#4]
Command line is good but I think that it will be more helpful using github UI with some images in update hubpress section.

After watching youtube video described in that section, I write post  about
[Update HubPress](https://dakeshi.github.io/2016/02/18/Maintain-your-Hub-Press-with-the-latest-version.html) 

What do you think about it?

**Comment by jaredmorgs** [comment]
Thanks for converting this blog post into HubPress documentation, @dakeshi
