### ISSUE TITLE
0.5.0 New Feature Summary

### ISSUE THREAD

**Issue by jaredmorgs** [HubPress/dev.hubpress.io#9]
Brief new feature summaries go here for the 0.5.0

List so far:

* delete post 
* user profiles
* PouchDB 
* Theme name standardisation

Please elaborate on any of these features in comments, or add new features to be covered.

**Comment by anthonny** [comment]
There is also:

* HubPress is now explode in plugins
* Use Redux

**Comment by anthonny** [comment]
NB: The first thing to do after the update is to resave settings to force generation and use the theme with lowercase

**Comment by jaredmorgs** [comment]
So we could put the info about Exploded Plug-ins and [Redux]https://github.com/reactjs/redux in as a Development Update.

What do you want to say specifically about the Exploded Plug-ins and HubPress Orchestrator?

Are these features actually in 0.5.0? Or will they feature in 0.6.0?

**Comment by jaredmorgs** [comment]
So regarding the "first actions" a user should take, we are not going to do these automatically. A user must manually:

- Check the case of the theme name they have specified in the settings.
- Resave settings to force the static site to regenerate.

**Comment by dakeshi** [comment]
It's great. Specially, save contents feature is important for contents writers. :+1: 
And Redux is one of the most hot library in web dev community.

Ready to translation. :laughing:

**Comment by anthonny** [comment]
The 0.5.1 is out now, can we close this issue?

**Comment by jaredmorgs** [comment]
Yep.

On Wed, 22 Jun 2016, 19:57 Anthonny Quérouil <notifications@github.com>
wrote:

> The 0.5.1 is out now, can we close this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HubPress/dev.hubpress.io/issues/9#issuecomment-227697853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA6J2Scv3dkRnybVPsfgxomRhnlxHLt2ks5qOQb3gaJpZM4HqoCT>
> .
>
-- 

Sent from Mobile.
